kind: pipline
name: demo

steps:
- name: step1
  image: maven
  volumes:
  #- name: dependency
  - path: /root/.m2:/root/.m2
  #- name: configuration
  - path: /drone/src/back-end/src/main/resources/application.yml:/Gusabary/back-end/src/main/resources/application.yml
  commands:
  - cd back-end
  - mvn clean
  - mvn test

#volumes:
#- name: dependency
#  host:
#    path: /root/.m2
#- name: configuration
#  host:
#    path: /Gusabary/back-end/src/main/resources/application.yml