kind: pipline
name: demo

steps:
- name: test
  image: maven
  volumes:
  - name: dependency
    path: /root/.m2
  - name: configuration
    path: /drone/src/back-end/src/main/resources/application.yml
  - name: secret
    path: /drone/src/back-end/src/main/java/com/example/demo/secret
  commands:
  - cd back-end
  - mvn clean
  - mvn test
  - mvn package

- name: upload
  image: appleboy/drone-scp
  settings:
    host: 47.100.126.180
    username: root
    password:
      from_secret: ssh_password
    rm: true
    target: /Gusabary/YIBUK-back-end
    source:
    - back-end/target/docker_spring_boot.jar
    - back-end/Dockerfile

- name: deploy
  iamge: appleboy/drone-ssh
  settings:
    host: 47.100.126.180
    username: root
    password:
      from_secret: ssh_password
    script:
    - cd /Gusabary/YIBUK-back-end/back-end/target
    - cp ../Dockerfile .
    - docker build -t yibuk-backend .
    - docker rm -f yibuk-backend-c
    - docker run -d --name yibuk-backend-c -p 8080:8080 yibuk-backend
      

volumes:
- name: dependency
  host:
    path: /root/.m2
- name: configuration
  host:
    path: /Gusabary/back-end/src/main/resources/application.yml
- name: secret
  host:
    path: /Gusabary/back-end/src/main/java/com/example/demo/secret