kind: pipline
name: demo

steps:
- name: step1
  image: maven
  volumes:
  - name: dependency
    path: /root/.m2
  commands:
  - cd back-end
  - mvn clean
  - mvn test -q

volumes:
- name: dependency
  host:
    path: /root/.m2