spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        # this strategy makes my column name mapping correct
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        # print Hibernate sql statements on console if true
        show_sql: false
        # wrap table and column name with `` to differentiate with reserved word
        globally_quoted_identifiers: true
  datasource:
    username: root
    password: my-password-here
    url: jdbc:mysql://47.100.126.180:3306/YIBUK?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver

